In [2]:
import pandas as pd

# Load datasets
df_class = pd.read_csv("/content/classification_dataset.csv")
df_reg = pd.read_csv("/content/regression_dataset.csv")

# Display first few rows
print(df_class.head())
print(df_reg.head())

   num_feature_0  num_feature_1  num_feature_2  num_feature_3  num_feature_4  \
0       1.296784       1.624245      -1.701435       1.914424       2.291332
1      -3.017773       0.446114      -0.587536      -0.028872      -4.266462
2       2.199807       5.949546       1.074338       2.550709       4.599309
3       6.705731       2.972102      -1.014667       1.545205       1.202765
4       0.240569       2.235346       1.483471      -2.363502      -2.903613

   num_feature_5  num_feature_6  num_feature_7  num_feature_8  num_feature_9  \
0      -1.285399       0.060932      -2.205755      -0.671176       4.349961
1      -0.069569       5.264937      -2.459792       0.509269       5.954572
2      -0.716514      -6.820298      -1.027973      -1.890677      -0.622828
3      -0.636449       6.516030      -0.972283      -4.949821       9.361150
4       1.990263      17.058229      -0.569073      -4.890264      13.079722

   ...  num_feature_44  num_feature_45  num_feature_46  num_feature_47  \
0  ...       14.522138       -1.078971       -0.334620        4.920558
1  ...        5.416666       -0.684955       -0.963690        2.406088
2  ...       -5.079558       -4.933970        0.352937        1.575021
3  ...        6.494306       -7.296286        2.162080        0.329687
4  ...        4.427922       -1.674425        1.973537       -4.486453

   num_feature_48  num_feature_49  gender  job_role         city  \
0       -7.614496       -2.297222    Male    Doctor      Chicago
1       -2.592075       -0.567436  Female    Artist      Houston
2        1.725213        1.824788    Male  Engineer  Los Angeles
3       -5.209867       -3.418690    Male  Engineer      Houston
4       -2.546136       -0.850080    Male  Engineer      Houston

   classification_target
0                      1
1                      0
2                      0
3                      1
4                      0

[5 rows x 54 columns]
   num_feature_0  num_feature_1  num_feature_2  num_feature_3  num_feature_4  \
0       0.222105       0.623867      -0.166056       0.634630       0.753769
1       0.830571      -1.716694      -0.155013       1.114356      -0.825304
2      -0.963353       0.543793      -1.113140       1.212359       0.552067
3       2.149843      -0.104679      -0.437220      -0.339445       1.178275
4      -0.537291       0.068838      -0.491454      -2.145759      -0.987731

   num_feature_5  num_feature_6  num_feature_7  num_feature_8  num_feature_9  \
0       1.658592      -0.701898       0.183612      -2.081954       0.602863
1       0.609160      -0.068017      -0.719405      -0.050230      -1.143785
2      -0.910265      -0.856090       0.533908       0.386812       0.257478
3       0.605398       0.626042       0.026819      -0.596114      -0.325793
4      -0.433522       0.315882       0.464362      -0.791415      -0.208447

   ...  num_feature_44  num_feature_45  num_feature_46  num_feature_47  \
0  ...       -0.112832       -0.363896        0.105162       -0.536786
1  ...       -0.514554       -0.145462        0.740684        0.851548
2  ...       -0.821580       -0.800445       -1.554154       -0.795955
3  ...        0.504989       -0.005484       -0.584365        0.761514
4  ...        1.412016        1.565019        1.349360       -0.759151

   num_feature_48  num_feature_49  gender  job_role         city  \
0       -0.057244       -0.300341    Male    Doctor      Chicago
1       -0.720188       -0.399939  Female    Artist      Houston
2        0.856455       -0.137110    Male  Engineer  Los Angeles
3       -0.756766       -1.260378    Male  Engineer      Houston
4       -0.915610        0.183969    Male  Engineer      Houston

   regression_target
0         144.233439
1          -9.153694
2         137.638484
3         -11.492067
4         -86.506285

[5 rows x 54 columns]

In [3]:
from sklearn.preprocessing import OneHotEncoder

# Select categorical columns
categorical_cols = ["gender", "job_role", "city"]

# One-hot encoding
df_class = pd.get_dummies(df_class, columns=categorical_cols, drop_first=True)
df_reg = pd.get_dummies(df_reg, columns=categorical_cols, drop_first=True)

In [4]:
from sklearn.model_selection import train_test_split

# For classification
X_class = df_class.drop("classification_target", axis=1)
y_class = df_class["classification_target"]
X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(X_class, y_class, test_size=0.2, random_state=42)

# For regression
X_reg = df_reg.drop("regression_target", axis=1)
y_reg = df_reg["regression_target"]
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_class, y_train_class)

y_pred_class = clf.predict(X_test_class)

# Evaluate performance
print("Accuracy:", accuracy_score(y_test_class, y_pred_class))
print("Classification Report:\n", classification_report(y_test_class, y_pred_class))

Accuracy: 0.845
Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.81      0.83        95
           1       0.84      0.88      0.86       105

    accuracy                           0.84       200
   macro avg       0.85      0.84      0.84       200
weighted avg       0.85      0.84      0.84       200

In [6]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

reg = RandomForestRegressor(n_estimators=100, random_state=42)
reg.fit(X_train_reg, y_train_reg)

y_pred_reg = reg.predict(X_test_reg)

# Evaluate performance
print("Mean Squared Error:", mean_squared_error(y_test_reg, y_pred_reg))
print("R2 Score:", r2_score(y_test_reg, y_pred_reg))

Mean Squared Error: 2822.262628798612
R2 Score: 0.8918100803971588